{{- if not(empty .Values.architect.namespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.architect.namespace }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: architect-{{ include "chart.name" . }}
  {{- if not (empty .Values.architect.namespace) }}
  namespace: {{ .Values.architect.namespace }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    program: architect
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      program: architect
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        program: architect
    spec:
      serviceAccountName: architect-sa
      containers:
        - name: architect-{{ .Chart.Name }}
          image: "{{ .Values.architect.image.repository }}:{{ .Values.architect.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.architect.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MATRIX_NAMESPACE
              {{- if (empty .Values.architect.namespace) }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
              {{- else}}
              value: {{ .Values.architect.namespace }}
              {{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: architect
  {{- if not (empty .Values.architect.namespace) }}
  namespace: {{ .Values.architect.namespace }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.architect.service.type }}
  ports:
    - port: {{ .Values.architect.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    program: architect
    {{- include "chart.selectorLabels" . | nindent 4 }}