{{- if .Values.oracle.enabled }}
{{- if .Values.oracle.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-cm
  {{- if not (empty .Values.oracle.namespace) }}
  namespace: {{ .Values.oracle.namespace }}
  {{- end }}
  labels:
    program: oracle
    application: matrix
data:
  oracle-config.yaml: |-
    names:
    {{- range .Values.oracle.config.names }}
      - {{ . | quote }}
    {{- end }}
    predictions:
    {{- range .Values.oracle.config.predictions }}
      - {{ . | quote }}
    {{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-{{ include "chart.name" . }}
  {{- if not (empty .Values.oracle.namespace) }}
  namespace: {{ .Values.oracle.namespace }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    program: oracle
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      program: oracle
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        program: oracle
    spec:
      containers:
        - name: oracle-{{ .Chart.Name }}
          image: "{{ .Values.oracle.image.repository }}:{{ .Values.oracle.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.oracle.image.pullPolicy }}
          {{- if .Values.oracle.config }}
          env:
            - name: EXTERNAL_CONFIGURATION
              value: /data/config/oracle-config.yaml
          volumeMounts:
            - name: oracle-config
              mountPath: /data/config
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      {{- if .Values.oracle.config }}
      volumes:
        - name: oracle-config
          configMap:
            name: oracle-cm
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: oracle
  {{- if not (empty .Values.oracle.namespace) }}
  namespace: {{ .Values.oracle.namespace }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.oracle.service.type }}
  ports:
    - port: {{ .Values.oracle.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    program: oracle
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}