{{- if .Values.oracle.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-{{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    program: oracle
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      program: oracle
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        program: oracle
    spec:
      containers:
        - name: oracle-{{ .Chart.Name }}
          image: "{{ .Values.oracle.image.repository }}:{{ .Values.oracle.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.oracle.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-{{- include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.oracle.service.type }}
  ports:
    - port: {{ .Values.oracle.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    program: oracle
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}