apiVersion: apps/v1
kind: Deployment
metadata:
  name: twins-{{ include "chart.name" . }}
  {{- if not (empty .Values.twins.namespace) }}
  namespace: {{ .Values.twins.namespace }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    program: twins
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      program: twins
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        program: twins
    spec:
      containers:
        - name: twins-{{ .Chart.Name }}
          image: "{{ .Values.twins.image.repository }}:{{ .Values.twins.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.twins.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: twins
  {{- if not (empty .Values.twins.namespace) }}
  namespace: {{ .Values.twins.namespace }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.twins.service.type }}
  ports:
    - port: {{ .Values.twins.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    program: twins
    {{- include "chart.selectorLabels" . | nindent 4 }}