apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fanout-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /agent(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: agent
                port:
                  number: 8080
          - path: /agent-smith(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: agent-smith
                port:
                  number: 8080
          - path: /agent-brown(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: agent-brown
                port:
                  number: 8080
          - path: /agent-jones(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: agent-jones
                port:
                  number: 8080
          - path: /agent-jackson(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: agent-jackson
                port:
                  number: 8080
          - path: /agent-johnson(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: agent-johnson
                port:
                  number: 8080
          - path: /agent-thompson(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: agent-thompson
                port:
                  number: 8080
          - path: /agent(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: agent
                port:
                  number: 8080
          - path: /oracle(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: oracle
                port:
                  number: 8080
          - path: /architect(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: architect
                port:
                  number: 8080
          - path: /merovingian(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: merovingian
                port:
                  number: 8080