---
apiVersion: v1
kind: Namespace
metadata:
  name: matrix
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: architect-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: architect-sa
  namespace: matrix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: architect-sa
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: architect-sa
subjects:
- kind: ServiceAccount
  name: architect-sa
  namespace: default
- kind: ServiceAccount
  name: architect-sa
  namespace: matrix

